### PR TITLE
Fine-tuning current code

### PR DESCRIPTION
**Pull request by roosdebildt**

### CODE REVIEW

**Comment by emcoding** [comment]
Nice, teamie!

**Comment by emcoding** [comment]
@coaches : we are practicing now with reviewing eachother's code. :-) before we present it to you

**Comment by roosdebildt** [comment]
@F3PiX thanks for the review teamie!

About the error message: I did bring back the min length at some point, but then I didn't find it really necessary anymore.

About the helper: good job! looking forward to see how one should do this in a clean way!

About the seeds: look carefully. It DOES matter which topic belongs to each source ;) And the level is being randomized, isn't it?

**Comment by emcoding** [comment]
If it does matter, that's all the better for the new exercise. Like: it does matter also what supervisor is added to what team. :-)

**Comment by roosdebildt** [comment]
ok, I tried it in three different ways now since you asked me :p being creative with seeds. I'll try after lunch, is that ok?

**Comment by emcoding** [comment]
No hurry, it is not needed for this app yet.

**Comment by roosdebildt** [comment]
Ok so, should iterate over the seeds in yet another way, or it's ok like this?

**Comment by emcoding** [comment]
You don't _have to_ at all, I was thinking it is more fun to practice with DD arrays than boring text book stuff. It's up to you!

**Comment by roosdebildt** [comment]
haha we don't have to do anything! but I'll try in a bit :) :+1:

**Comment by emcoding** [comment]
I am closing the PR and merging it into master.

**Comment by roosdebildt** [comment]
yeay!

**Pull request merged**
